import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Script from 'next/script';
import Squares from './components/Squares/Squares';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Portofolio",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />
        <Script id="prevent-scroll" strategy="beforeInteractive">{`
          // Prevent scroll restoration
          if (history.scrollRestoration) {
            history.scrollRestoration = 'manual';
          }
          // Force scroll to top on page load
          window.scrollTo(0, 0);
        `}</Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div style={{ position: 'relative', minHeight: '100vh', overflow: 'hidden' }}>
          {/* Background Squares */}
          <div
            style={{
              position: 'absolute',
              inset: 0,
              zIndex: 0,
              pointerEvents: 'none',
            }}
          >
            <Squares
              direction="diagonal"
              speed={1}
              borderColor="rgba(199,234,70,0.5)"
              squareSize={40}
              hoverFillColor="#C7EA46"
            />
          </div>
          {/* Konten utama */}
          <div style={{ position: 'relative', zIndex: 1 }}>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
